# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'makine.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 120, 121, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 150, 121, 20))
        self.label_2.setObjectName("label_2")
        self.ilksayi = QtWidgets.QLineEdit(self.centralwidget)
        self.ilksayi.setGeometry(QtCore.QRect(190, 120, 113, 22))
        self.ilksayi.setObjectName("ilksayi")
        self.ikincisayi = QtWidgets.QLineEdit(self.centralwidget)
        self.ikincisayi.setGeometry(QtCore.QRect(190, 150, 113, 22))
        self.ikincisayi.setObjectName("ikincisayi")
        self.toplama_btn = QtWidgets.QPushButton(self.centralwidget)
        self.toplama_btn.setGeometry(QtCore.QRect(50, 230, 93, 28))
        self.toplama_btn.setObjectName("toplama_btn")
        self.cikarma_btn = QtWidgets.QPushButton(self.centralwidget)
        self.cikarma_btn.setGeometry(QtCore.QRect(160, 230, 93, 28))
        self.cikarma_btn.setObjectName("cikarma_btn")
        self.bolme_btn = QtWidgets.QPushButton(self.centralwidget)
        self.bolme_btn.setGeometry(QtCore.QRect(270, 230, 93, 28))
        self.bolme_btn.setObjectName("bolme_btn")
        self.carpma_btn = QtWidgets.QPushButton(self.centralwidget)
        self.carpma_btn.setGeometry(QtCore.QRect(380, 230, 93, 28))
        self.carpma_btn.setObjectName("carpma_btn")
        self.sonuc_lbl = QtWidgets.QLabel(self.centralwidget)
        self.sonuc_lbl.setGeometry(QtCore.QRect(340, 120, 191, 21))
        self.sonuc_lbl.setObjectName("sonuc_lbl")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "İlk Sayıyı Giriniz : "))
        self.label_2.setText(_translate("MainWindow", "İkinci Sayıyı Giriniz : "))
        self.toplama_btn.setText(_translate("MainWindow", "Toplama"))
        self.cikarma_btn.setText(_translate("MainWindow", "Çıkarma"))
        self.bolme_btn.setText(_translate("MainWindow", "Bölme"))
        self.carpma_btn.setText(_translate("MainWindow", "Çarpma"))
        self.sonuc_lbl.setText(_translate("MainWindow", "Sonuç : "))

